version: '3.5'

services:

  docker-info:
    build: .
    image: flaviostutz/docker-info
    environment:
      - LOG_LEVEL=debug
      - CACHE_TIMEOUT=-1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 5000:5000

  test1:
    image: alpine
    command: sleep 99999
    restart: always
    labels: 
      - "publicIp=222.33.44.55"
    ports:
      - target: 80
        protocol: tcp
        mode: host

