version: '3.5'

services:

  docker-info:
    build: .
    image: flaviostutz/docker-info2
    environment:
      - LOG_LEVEL=debug
      - CACHE_TIMEOUT=-1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - target: 5000
        published: 3384
        protocol: tcp
        mode: host

  test1:
    image: alpine
    command: sleep 99999
    restart: always
    labels: 
      - "publicIp=111.11.11.11"
    ports:
      - target: 80
        protocol: tcp
        mode: host

